name: Update Node.js Versions

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:
  push:

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: |
          JSON=$(jq -c '.versions | keys' versions.json)
          echo "matrix=$JSON" >> GITHUB_OUTPUT
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
          set_as_trusted_user: true
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v16
        with:
          name: nixpkgs-nodejs
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          pushFilter: "(-source$|\\.tar\\.gz$)"

      - run: nix profile add nixpkgs#nix-prefetch-git nixpkgs#jq

      - name: Caculate hashes
        run: |
          if ! command -v nix-prefetch-git &> /dev/null; then
              echo "FATAL: 'nix-prefetch-git' is not found."
              exit 1
          fi

          mapfile -t TO_UPDATE < <(jq -r '.versions | to_entries[] | select(.value.sha256 == "") | "\(.key) \(.value.rev)"' versions.json)

          if [ ${#TO_UPDATE[@]} -eq 0 ]; then
             echo "All versions already have hashes. Nothing to do."
             exit 0
          fi

          UPDATED_JSON=$(cat versions.json)

          for entry in "${TO_UPDATE[@]}"; do
              VERSION_KEY=$(echo "$entry" | cut -d' ' -f1)
              REV_HASH=$(echo "$entry" | cut -d' ' -f2)

              echo "Processing ${VERSION_KEY}..."

              NEW_SHA256=$(
                  nix-prefetch-git "https://github.com/NixOS/nixpkgs.git" "${REV_HASH}" \
                  --quiet --fetch-submodules | jq -r '.sha256'
              )

              if [ -n "$NEW_SHA256" ] && [ "$NEW_SHA256" != "null" ]; then
                  echo " -> Hash: $NEW_SHA256"
                  UPDATED_JSON=$(echo "$UPDATED_JSON" | jq \
                      --arg v "$VERSION_KEY" \
                      --arg sha "$NEW_SHA256" \
                      '.versions[$v] += {sha256: $sha}'
                  )
              else
                echo "::error::Failed to get hash for rev ${REV_HASH}. Skipping."
                exit 1
              fi
          done

          echo "$UPDATED_JSON" > versions.json
          echo "âœ“ versions.json updated successfully."

      - name: Build ${{ matrix.version }} version
        run: |
          TARGET_SYSTEM="x86_64-linux"

          nix build .#packages.$TARGET_SYSTEM."${{ matrix.version }}" --print-build-logs

      - name: Commit changes if changes to versions.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add versions.json
          git diff --quiet && git diff --staged --quiet || \
            (git commit -m "chore: update Node.js versions" && git push)
